In [1]:
import pandas as pd
import re

pd.set_option('display.max_columns', None)
database = pd.read_csv('C://Users//eduar//Desktop//DEV//Football//MLS//database.csv', delimiter=',')

## Inicial

In [2]:
database

,Jogador,Time,#,Nação,Pos.,Idade,Min.,Gols,Assis.,PB,PT,TC,CaG,CrtsA,CrtV,Contatos,Div,Crts,Bloqueios,xG,npxG,xAG,SCA,GCA,Cmp,Att,Cmp%,PrgP,Conduções,PrgC,Tent,Suc,Data
0,Luis Suárez,Inter Miami,9,URU,FW,37-028,89,0,1,0,0,2,2,0,0,37,0,0,1,0.3,0.3,0.4,6,1,22,31,"71,0",3,24,1,1,1,2024-02-21
1,Leonardo Campana,Inter Miami,8,ECU,FW,23-212,1,0,0,0,0,0,0,0,0,2,0,0,0,0.0,0.0,0.0,0,0,1,2,"50,0",0,1,0,0,0,2024-02-21
2,Robert Taylor,Inter Miami,16,FIN,LW,29-123,75,1,0,0,0,2,1,0,0,31,0,2,1,0.1,0.1,0.2,3,0,20,26,"76,9",2,18,0,2,2,2024-02-21
3,David Ruiz,Inter Miami,41,HON,RM,20-013,15,0,0,0,0,0,0,0,0,11,0,1,0,0.0,0.0,0.0,0,0,10,10,"100,0",0,8,0,0,0,2024-02-21
4,Lionel Messi,Inter Miami,10,ARG,"RW,FW",36-242,90,0,1,0,0,4,1,0,0,84,1,0,0,0.5,0.5,0.2,10,2,56,73,"76,7",15,55,6,4,2,2024-02-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12828,Jere Uronen,Charlotte FC,21,FIN,LB,30-067,90,0,0,0,0,0,0,0,0,61,1,1,1,0.0,0.0,0.0,0,0,47,54,"87,0",5,24,1,0,0,2024-09-18
12829,Tim Ream,Charlotte FC,3,USA,CB,36-349,90,0,0,0,0,1,0,0,0,51,0,2,2,0.1,0.1,0.0,0,0,34,41,"82,9",5,28,0,0,0,2024-09-18
12830,Adilson Malanda,Charlotte FC,29,FRA,CB,22-325,90,0,0,0,0,0,0,0,0,59,0,3,0,0.0,0.0,0.0,0,0,47,51,"92,2",6,37,0,0,0,2024-09-18
12831,Nathan Byrne,Charlotte FC,14,ENG,RB,32-105,90,0,0,0,0,0,0,0,0,63,0,1,1,0.0,0.0,0.1,2,0,46,58,"79,3",2,45,0,0,0,2024-09-18
12832,Kristijan Kahlina,Charlotte FC,1,CRO,GK,32-056,90,0,0,0,0,0,0,0,0,27,0,0,0,0.0,0.0,0.0,0,0,14,25,"56,0",0,15,0,0,0,2024-09-18

In [27]:
database[database['Jogador'].isin(['Evander','Felipe Mora'])].tail(10)

,Jogador,Time,#,Nação,Pos.,Idade,Min.,Gols,Assis.,PB,PT,TC,CaG,CrtsA,CrtV,Contatos,Div,Crts,Bloqueios,xG,npxG,xAG,SCA,GCA,Cmp,Att,Cmp%,PrgP,Conduções,PrgC,Tent,Suc,Data
9834,Evander,Portland Timbers,10,BRA,AM,26-034,90,1,1,0,0,5,1,0,0,69,1,0,1,0.3,0.3,0.4,9,1,38,49,"77,6",9,41,6,6,2,2024-07-13
10954,Felipe Mora,Portland Timbers,9,CHI,FW,30-353,63,0,0,0,0,0,0,0,0,14,0,1,1,0.0,0.0,0.1,1,0,9,11,"81,8",0,4,0,1,1,2024-07-20
10959,Evander,Portland Timbers,10,BRA,AM,26-041,90,0,1,0,0,5,1,1,0,89,1,0,1,0.5,0.5,0.1,4,1,55,73,"75,3",13,43,4,4,0,2024-07-20
11247,Felipe Mora,Portland Timbers,9,CHI,FW,31-022,89,2,1,0,0,7,3,0,1,34,0,0,0,1.5,1.5,0.8,5,1,21,25,"84,0",2,13,1,1,1,2024-08-24
11250,Evander,Portland Timbers,10,BRA,AM,26-076,90,1,1,0,0,6,4,1,0,86,0,0,0,0.3,0.3,0.8,12,4,45,76,"59,2",10,40,3,4,2,2024-08-24
11597,Evander,Portland Timbers,10,BRA,"AM,FW",26-083,89,0,1,0,0,2,1,0,0,67,2,2,0,0.1,0.1,0.3,8,1,42,55,"76,4",7,37,3,4,2,2024-08-31
12413,Felipe Mora,Portland Timbers,9,CHI,"LW,FW",31-043,22,0,0,0,0,1,1,0,0,4,0,0,0,0.3,0.3,0.0,0,0,3,3,"100,0",0,1,0,0,0,2024-09-14
12415,Evander,Portland Timbers,10,BRA,AM,26-097,90,0,0,0,0,3,2,0,0,47,1,1,0,0.1,0.1,0.8,6,0,23,35,"65,7",3,23,5,7,2,2024-09-14
12642,Felipe Mora,Portland Timbers,9,CHI,FW,31-047,84,1,0,0,0,3,2,0,0,28,2,1,0,0.3,0.3,0.2,2,1,15,20,"75,0",3,18,1,1,0,2024-09-18
12647,Evander,Portland Timbers,10,BRA,AM,26-101,90,2,1,0,0,10,5,0,0,68,1,0,0,1.6,1.6,0.6,5,2,38,47,"80,9",4,39,4,5,1,2024-09-18

## Agrupado Jogador

In [3]:
# Agrupar os dados por jogador e calcular a soma dos chutes ao gol e a contagem de aparições
db_agrupado_jogador = database.groupby(['Jogador','Time'], as_index= False).agg(
    Total_Gols=('Gols','sum'),
    Total_Chutes=('TC', 'sum'),   # Soma dos chutes ao gol
    Aparicoes=('Jogador', 'count'), # Contagem de aparições
    Total_Chutes_Gol=('CaG', 'sum') # Contagem de aparições
)

In [4]:
db_agrupado_jogador['Média_chute']=round(db_agrupado_jogador['Total_Chutes'] / db_agrupado_jogador['Aparicoes'],2)
db_agrupado_jogador['Média_chute_Gol']=round(db_agrupado_jogador['Total_Chutes_Gol'] / db_agrupado_jogador['Aparicoes'],2)
db_agrupado_jogador['Média_gol']=round(db_agrupado_jogador['Total_Gols'] / db_agrupado_jogador['Aparicoes'],2)
db_agrupado_jogador['Taxa_Chutes_Gol'] = db_agrupado_jogador['Total_Chutes_Gol'] / db_agrupado_jogador['Total_Chutes']

In [32]:
filtro = db_agrupado_jogador['Aparicoes']>6
db_agrupado_jogador[filtro].sort_values(by='Média_chute', ascending=False, ignore_index= True).head(20)

,Jogador,Time,Total_Gols,Total_Chutes,Aparicoes,Total_Chutes_Gol,Média_chute,Média_chute_Gol,Média_gol,Taxa_Chutes_Gol
0,Cucho,Columbus Crew,14,107,22,29,4.86,1.32,0.64,0.271028
1,Denis Bouanga,Los Angeles FC,17,123,27,39,4.56,1.44,0.63,0.317073
2,Lionel Messi,Inter Miami,14,63,14,28,4.50,2.00,1.00,0.444444
3,Cristian Arango,Real Salt Lake,17,101,25,36,4.04,1.44,0.68,0.356436
4,Julián Carranza,Philadelphia Union,6,45,12,15,3.75,1.25,0.50,0.333333
5,Tomás Chancalay,New England Revolution,2,45,12,15,3.75,1.25,0.17,0.333333
6,Riqui Puig,LA Galaxy,10,89,25,29,3.56,1.16,0.40,0.325843
7,Gabriel Chaves,LA Galaxy,12,103,29,47,3.55,1.62,0.41,0.456311
8,Giorgos Giakoumakis,Atlanta United,5,39,11,11,3.55,1.00,0.45,0.282051
9,Federico Bernardeschi,Toronto FC,8,87,26,30,3.35,1.15,0.31,0.344828
10,Lewis Morgan,New York Red Bulls,12,78,24,26,3.25,1.08,0.50,0.333333
11,Evander,Portland Timbers,14,77,24,33,3.21,1.38,0.58,0.428571
12,Raúl Ruidíaz,Seattle Sounders FC,8,73,23,26,3.17,1.13,0.35,0.356164
13,Jonathan Rodríguez,Portland Timbers,14,76,24,33,3.17,1.38,0.58,0.434211
14,Klauss,St. Louis City,5,68,22,17,3.09,0.77,0.23,0.250000
15,Thiago Almada,Atlanta United,6,52,17,18,3.06,1.06,0.35,0.346154
16,Carlos Gómez,Real Salt Lake,13,68,23,32,2.96,1.39,0.57,0.470588
17,Petar Musa,FC Dallas,14,77,26,25,2.96,0.96,0.54,0.324675
18,Cristian Olivera,Los Angeles FC,5,52,18,24,2.89,1.33,0.28,0.461538
19,Christian Benteke,D.C. United,19,72,25,33,2.88,1.32,0.76,0.458333

In [28]:
database[database['Jogador'].isin(['Evander','Felipe Mora'])].tail(10)

,Jogador,Time,#,Nação,Pos.,Idade,Min.,Gols,Assis.,PB,PT,TC,CaG,CrtsA,CrtV,Contatos,Div,Crts,Bloqueios,xG,npxG,xAG,SCA,GCA,Cmp,Att,Cmp%,PrgP,Conduções,PrgC,Tent,Suc,Data
9834,Evander,Portland Timbers,10,BRA,AM,26-034,90,1,1,0,0,5,1,0,0,69,1,0,1,0.3,0.3,0.4,9,1,38,49,"77,6",9,41,6,6,2,2024-07-13
10954,Felipe Mora,Portland Timbers,9,CHI,FW,30-353,63,0,0,0,0,0,0,0,0,14,0,1,1,0.0,0.0,0.1,1,0,9,11,"81,8",0,4,0,1,1,2024-07-20
10959,Evander,Portland Timbers,10,BRA,AM,26-041,90,0,1,0,0,5,1,1,0,89,1,0,1,0.5,0.5,0.1,4,1,55,73,"75,3",13,43,4,4,0,2024-07-20
11247,Felipe Mora,Portland Timbers,9,CHI,FW,31-022,89,2,1,0,0,7,3,0,1,34,0,0,0,1.5,1.5,0.8,5,1,21,25,"84,0",2,13,1,1,1,2024-08-24
11250,Evander,Portland Timbers,10,BRA,AM,26-076,90,1,1,0,0,6,4,1,0,86,0,0,0,0.3,0.3,0.8,12,4,45,76,"59,2",10,40,3,4,2,2024-08-24
11597,Evander,Portland Timbers,10,BRA,"AM,FW",26-083,89,0,1,0,0,2,1,0,0,67,2,2,0,0.1,0.1,0.3,8,1,42,55,"76,4",7,37,3,4,2,2024-08-31
12413,Felipe Mora,Portland Timbers,9,CHI,"LW,FW",31-043,22,0,0,0,0,1,1,0,0,4,0,0,0,0.3,0.3,0.0,0,0,3,3,"100,0",0,1,0,0,0,2024-09-14
12415,Evander,Portland Timbers,10,BRA,AM,26-097,90,0,0,0,0,3,2,0,0,47,1,1,0,0.1,0.1,0.8,6,0,23,35,"65,7",3,23,5,7,2,2024-09-14
12642,Felipe Mora,Portland Timbers,9,CHI,FW,31-047,84,1,0,0,0,3,2,0,0,28,2,1,0,0.3,0.3,0.2,2,1,15,20,"75,0",3,18,1,1,0,2024-09-18
12647,Evander,Portland Timbers,10,BRA,AM,26-101,90,2,1,0,0,10,5,0,0,68,1,0,0,1.6,1.6,0.6,5,2,38,47,"80,9",4,39,4,5,1,2024-09-18

## Agrupado Time

In [15]:
sorted(database.Time.unique())

['Atlanta United',
 'Austin FC',
 'CF Montréal',
 'Charlotte FC',
 'Chicago Fire',
 'Colorado Rapids',
 'Columbus Crew',
 'D.C. United',
 'FC Cincinnati',
 'FC Dallas',
 'Houston Dynamo',
 'Inter Miami',
 'LA Galaxy',
 'Los Angeles FC',
 'Minnesota United',
 'Nashville SC',
 'New England Revolution',
 'New York City FC',
 'New York Red Bulls',
 'Orlando City',
 'Philadelphia Union',
 'Portland Timbers',
 'Real Salt Lake',
 'San Jose Earthquakes',
 'Seattle Sounders FC',
 'Sporting Kansas City',
 'St. Louis City',
 'Toronto FC',
 'Vancouver Whitecaps FC']

In [7]:
db_agrupado_time = database.groupby(['Time'], as_index=False).agg(
    Total_Gols=('Gols', 'sum'),
    Total_Chutes=('TC', 'sum'),   # Soma dos chutes ao gol
    Aparicoes=('Data', 'nunique'), # Contagem de jogos únicos (datas únicas)
    Total_Chutes_Gol=('CaG', 'sum') # Soma dos chutes ao gol
)

In [8]:
db_agrupado_time['Média_chute']=round(db_agrupado_time['Total_Chutes'] / db_agrupado_time['Aparicoes'],2)
db_agrupado_time['Média_chute_gol']=round(db_agrupado_time['Total_Chutes_Gol'] / db_agrupado_time['Aparicoes'],2)
db_agrupado_time['Média_gol']=round(db_agrupado_time['Total_Gols'] / db_agrupado_time['Aparicoes'],2)
db_agrupado_time['Taxa_Chutes_Gol'] = db_agrupado_time['Total_Chutes_Gol'] / db_agrupado_time['Total_Chutes']

In [22]:
db_agrupado_time.sort_values(by='Média_chute_gol', ascending=False)

,Time,Total_Gols,Total_Chutes,Aparicoes,Total_Chutes_Gol,Média_chute,Média_chute_gol,Média_gol,Taxa_Chutes_Gol
13,Los Angeles FC,50,435,28,164,15.54,5.86,1.79,0.377011
12,LA Galaxy,59,431,30,173,14.37,5.77,1.97,0.401392
22,Real Salt Lake,56,447,29,161,15.41,5.55,1.93,0.360179
11,Inter Miami,66,338,29,154,11.66,5.31,2.28,0.455621
8,FC Cincinnati,50,406,29,153,14.00,5.28,1.72,0.376847
20,Philadelphia Union,53,438,29,152,15.10,5.24,1.83,0.347032
21,Portland Timbers,59,395,29,146,13.62,5.03,2.03,0.369620
18,New York Red Bulls,43,424,29,145,14.62,5.00,1.48,0.341981
0,Atlanta United,37,426,29,140,14.69,4.83,1.28,0.328638
26,St. Louis City,38,451,29,139,15.55,4.79,1.31,0.308204
6,Columbus Crew,54,379,28,134,13.54,4.79,1.93,0.353562
14,Minnesota United,46,384,29,138,13.24,4.76,1.59,0.359375
10,Houston Dynamo,40,399,29,137,13.76,4.72,1.38,0.343358
17,New York City FC,42,396,29,132,13.66,4.55,1.45,0.333333
5,Colorado Rapids,52,358,29,132,12.34,4.55,1.79,0.368715
28,Vancouver Whitecaps FC,46,358,28,126,12.79,4.50,1.64,0.351955
7,D.C. United,44,392,29,130,13.52,4.48,1.52,0.331633
16,New England Revolution,32,335,28,121,11.96,4.32,1.14,0.361194
24,Seattle Sounders FC,43,404,30,128,13.47,4.27,1.43,0.316832
9,FC Dallas,44,346,29,123,11.93,4.24,1.52,0.355491
19,Orlando City,44,380,29,122,13.10,4.21,1.52,0.321053
25,Sporting Kansas City,49,406,30,126,13.53,4.20,1.63,0.310345
4,Chicago Fire,36,359,30,124,11.97,4.13,1.20,0.345404
27,Toronto FC,36,335,30,118,11.17,3.93,1.20,0.352239
3,Charlotte FC,31,304,29,107,10.48,3.69,1.07,0.351974
2,CF Montréal,37,311,29,107,10.72,3.69,1.28,0.344051
23,San Jose Earthquakes,34,352,29,105,12.14,3.62,1.17,0.298295
15,Nashville SC,28,310,29,89,10.69,3.07,0.97,0.287097
1,Austin FC,32,265,29,80,9.14,2.76,1.10,0.301887

In [23]:
db_agrupado_time[db_agrupado_time['Time'].isin(['Los Angeles FC','LA Galaxy','Portland Timbers','FC Cincinnati'])].sort_values(by='Total_Chutes', ascending=False, ignore_index= True)

,Time,Total_Gols,Total_Chutes,Aparicoes,Total_Chutes_Gol,Média_chute,Média_chute_gol,Média_gol,Taxa_Chutes_Gol
0,Los Angeles FC,50,435,28,164,15.54,5.86,1.79,0.377011
1,LA Galaxy,59,431,30,173,14.37,5.77,1.97,0.401392
2,FC Cincinnati,50,406,29,153,14.00,5.28,1.72,0.376847
3,Portland Timbers,59,395,29,146,13.62,5.03,2.03,0.369620

## Agrupado por Data

In [10]:
db_desempenho_por_data = database.groupby(['Time', 'Data'], as_index=False).agg(
    Total_Gols=('Gols', 'sum'),          # Soma de gols por data
    Total_Chutes=('TC', 'sum'),          # Soma de chutes por data
    Total_Chutes_Gol=('CaG', 'sum')      # Soma dos chutes ao gol por data
).sort_values(by=['Time', 'Data'])

In [11]:
db_desempenho_por_data['Taxa_Chutes'] = round(db_desempenho_por_data['Total_Gols'] / db_desempenho_por_data['Total_Chutes'],4)
db_desempenho_por_data['Taxa_Chutes_Gol'] = round(db_desempenho_por_data['Total_Gols'] / db_desempenho_por_data['Total_Chutes_Gol'],4)

In [12]:
db_desempenho_por_data[db_desempenho_por_data['Time'].isin(['Los Angeles FC'])].tail(10)

,Time,Data,Total_Gols,Total_Chutes,Total_Chutes_Gol,Taxa_Chutes,Taxa_Chutes_Gol
396,Los Angeles FC,2024-06-22,6,25,8,0.2400,0.7500
397,Los Angeles FC,2024-06-29,3,22,11,0.1364,0.2727
398,Los Angeles FC,2024-07-04,2,21,6,0.0952,0.3333
399,Los Angeles FC,2024-07-13,1,17,5,0.0588,0.2000
400,Los Angeles FC,2024-07-17,1,9,5,0.1111,0.2000
401,Los Angeles FC,2024-07-20,3,6,4,0.5000,0.7500
402,Los Angeles FC,2024-08-31,0,14,6,0.0000,0.0000
403,Los Angeles FC,2024-09-07,0,7,2,0.0000,0.0000
404,Los Angeles FC,2024-09-14,2,15,5,0.1333,0.4000
405,Los Angeles FC,2024-09-18,1,13,6,0.0769,0.1667

In [13]:
db_desempenho_por_data[db_desempenho_por_data['Time'].isin(['Austin FC'])].tail(10)

,Time,Data,Total_Gols,Total_Chutes,Total_Chutes_Gol,Taxa_Chutes,Taxa_Chutes_Gol
48,Austin FC,2024-06-22,1,9,3,0.1111,0.3333
49,Austin FC,2024-06-29,0,2,0,0.0000,NaN
50,Austin FC,2024-07-06,2,9,4,0.2222,0.5000
51,Austin FC,2024-07-13,0,13,4,0.0000,0.0000
52,Austin FC,2024-07-17,1,11,4,0.0909,0.2500
53,Austin FC,2024-07-20,2,11,4,0.1818,0.5000
54,Austin FC,2024-08-24,2,15,6,0.1333,0.3333
55,Austin FC,2024-08-31,0,6,0,0.0000,NaN
56,Austin FC,2024-09-14,1,17,6,0.0588,0.1667
57,Austin FC,2024-09-18,1,10,2,0.1000,0.5000

In [14]:
database

,Jogador,Time,#,Nação,Pos.,Idade,Min.,Gols,Assis.,PB,PT,TC,CaG,CrtsA,CrtV,Contatos,Div,Crts,Bloqueios,xG,npxG,xAG,SCA,GCA,Cmp,Att,Cmp%,PrgP,Conduções,PrgC,Tent,Suc,Data
0,Luis Suárez,Inter Miami,9,URU,FW,37-028,89,0,1,0,0,2,2,0,0,37,0,0,1,0.3,0.3,0.4,6,1,22,31,"71,0",3,24,1,1,1,2024-02-21
1,Leonardo Campana,Inter Miami,8,ECU,FW,23-212,1,0,0,0,0,0,0,0,0,2,0,0,0,0.0,0.0,0.0,0,0,1,2,"50,0",0,1,0,0,0,2024-02-21
2,Robert Taylor,Inter Miami,16,FIN,LW,29-123,75,1,0,0,0,2,1,0,0,31,0,2,1,0.1,0.1,0.2,3,0,20,26,"76,9",2,18,0,2,2,2024-02-21
3,David Ruiz,Inter Miami,41,HON,RM,20-013,15,0,0,0,0,0,0,0,0,11,0,1,0,0.0,0.0,0.0,0,0,10,10,"100,0",0,8,0,0,0,2024-02-21
4,Lionel Messi,Inter Miami,10,ARG,"RW,FW",36-242,90,0,1,0,0,4,1,0,0,84,1,0,0,0.5,0.5,0.2,10,2,56,73,"76,7",15,55,6,4,2,2024-02-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12828,Jere Uronen,Charlotte FC,21,FIN,LB,30-067,90,0,0,0,0,0,0,0,0,61,1,1,1,0.0,0.0,0.0,0,0,47,54,"87,0",5,24,1,0,0,2024-09-18
12829,Tim Ream,Charlotte FC,3,USA,CB,36-349,90,0,0,0,0,1,0,0,0,51,0,2,2,0.1,0.1,0.0,0,0,34,41,"82,9",5,28,0,0,0,2024-09-18
12830,Adilson Malanda,Charlotte FC,29,FRA,CB,22-325,90,0,0,0,0,0,0,0,0,59,0,3,0,0.0,0.0,0.0,0,0,47,51,"92,2",6,37,0,0,0,2024-09-18
12831,Nathan Byrne,Charlotte FC,14,ENG,RB,32-105,90,0,0,0,0,0,0,0,0,63,0,1,1,0.0,0.0,0.1,2,0,46,58,"79,3",2,45,0,0,0,2024-09-18
12832,Kristijan Kahlina,Charlotte FC,1,CRO,GK,32-056,90,0,0,0,0,0,0,0,0,27,0,0,0,0.0,0.0,0.0,0,0,14,25,"56,0",0,15,0,0,0,2024-09-18