In [1]:
import pandas as pd
import re

pd.set_option('display.max_columns', None)
database = pd.read_csv('C://Users//eduar//Desktop//DEV//Football//MLS//database.csv', delimiter=',')

## Inicial

In [2]:
database

,Jogador,Time,#,Nação,Pos.,Idade,Min.,Gols,Assis.,PB,PT,TC,CaG,CrtsA,CrtV,Contatos,Div,Crts,Bloqueios,xG,npxG,xAG,SCA,GCA,Cmp,Att,Cmp%,PrgP,Conduções,PrgC,Tent,Suc,Data
0,Luis Suárez,Inter Miami,9,URU,FW,37-028,89,0,1,0,0,2,2,0,0,37,0,0,1,0.3,0.3,0.4,6,1,22,31,"71,0",3,24,1,1,1,2024-02-21
1,Leonardo Campana,Inter Miami,8,ECU,FW,23-212,1,0,0,0,0,0,0,0,0,2,0,0,0,0.0,0.0,0.0,0,0,1,2,"50,0",0,1,0,0,0,2024-02-21
2,Robert Taylor,Inter Miami,16,FIN,LW,29-123,75,1,0,0,0,2,1,0,0,31,0,2,1,0.1,0.1,0.2,3,0,20,26,"76,9",2,18,0,2,2,2024-02-21
3,David Ruiz,Inter Miami,41,HON,RM,20-013,15,0,0,0,0,0,0,0,0,11,0,1,0,0.0,0.0,0.0,0,0,10,10,"100,0",0,8,0,0,0,2024-02-21
4,Lionel Messi,Inter Miami,10,ARG,"RW,FW",36-242,90,0,1,0,0,4,1,0,0,84,1,0,0,0.5,0.5,0.2,10,2,56,73,"76,7",15,55,6,4,2,2024-02-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12419,Kamal Miller,Portland Timbers,4,CAN,LB,27-121,90,0,0,0,0,0,0,0,0,59,0,1,3,0.0,0.0,0.0,1,0,44,48,"91,7",5,20,1,2,0,2024-09-14
12420,Dario Župarić,Portland Timbers,13,BIH,CB,32-134,90,0,0,0,0,0,0,0,0,65,2,1,2,0.0,0.0,0.0,1,0,49,56,"87,5",4,31,0,0,0,2024-09-14
12421,Miguel Araujo,Portland Timbers,2,PER,CB,29-326,90,0,1,0,0,1,0,0,0,68,2,1,2,0.0,0.0,0.3,4,1,47,57,"82,5",2,35,0,1,0,2024-09-14
12422,Juan David Mosquera,Portland Timbers,29,COL,RB,22-009,90,0,0,0,0,1,0,0,0,51,1,0,1,0.0,0.0,0.0,2,0,41,45,"91,1",1,24,2,0,0,2024-09-14
12423,Maxime Crépeau,Portland Timbers,16,CAN,GK,30-126,90,0,0,0,0,0,0,0,0,38,0,0,0,0.0,0.0,0.0,0,0,28,37,"75,7",1,25,0,0,0,2024-09-14

## Agrupado Jogador

In [3]:
# Agrupar os dados por jogador e calcular a soma dos chutes ao gol e a contagem de aparições
db_agrupado_jogador = database.groupby(['Jogador','Time'], as_index= False).agg(
    Total_Gols=('Gols','sum'),
    Total_Chutes=('TC', 'sum'),   # Soma dos chutes ao gol
    Aparicoes=('Jogador', 'count'), # Contagem de aparições
    Total_Chutes_Gol=('CaG', 'sum') # Contagem de aparições
)

In [4]:
db_agrupado_jogador['Média_chute']=round(db_agrupado_jogador['Total_Chutes'] / db_agrupado_jogador['Aparicoes'],2)
db_agrupado_jogador['Média_chute_Gol']=round(db_agrupado_jogador['Total_Chutes_Gol'] / db_agrupado_jogador['Aparicoes'],2)
db_agrupado_jogador['Média_gol']=round(db_agrupado_jogador['Total_Gols'] / db_agrupado_jogador['Aparicoes'],2)
db_agrupado_jogador['Taxa_Chutes_Gol'] = db_agrupado_jogador['Total_Chutes_Gol'] / db_agrupado_jogador['Total_Chutes']

In [5]:
db_agrupado_jogador[db_agrupado_jogador['Time'].isin(['LA Galaxy','Portland Timbers'])].sort_values(by='Média_chute_Gol', ascending=False, ignore_index= True).head(20)

,Jogador,Time,Total_Gols,Total_Chutes,Aparicoes,Total_Chutes_Gol,Média_chute,Média_chute_Gol,Média_gol,Taxa_Chutes_Gol
0,Gabriel Chaves,LA Galaxy,11,97,28,44,3.46,1.57,0.39,0.453608
1,Jonathan Rodríguez,Portland Timbers,13,70,23,29,3.04,1.26,0.57,0.414286
2,Evander,Portland Timbers,12,67,23,28,2.91,1.22,0.52,0.417910
3,Riqui Puig,LA Galaxy,10,81,24,28,3.38,1.17,0.42,0.345679
4,Dejan Joveljić,LA Galaxy,14,47,23,26,2.04,1.13,0.61,0.553191
5,Marco Reus,LA Galaxy,1,5,3,3,1.67,1.00,0.33,0.600000
6,Joseph Paintsil,LA Galaxy,8,54,24,23,2.25,0.96,0.33,0.425926
7,Felipe Mora,Portland Timbers,13,48,23,21,2.09,0.91,0.57,0.437500
8,Mason Toye,Portland Timbers,0,6,3,2,2.00,0.67,0.00,0.333333
9,Santiago Moreno,Portland Timbers,6,47,26,15,1.81,0.58,0.23,0.319149
10,Diego Fagúndez,LA Galaxy,4,27,29,14,0.93,0.48,0.14,0.518519
11,Antony,Portland Timbers,4,34,27,11,1.26,0.41,0.15,0.323529
12,Gastón Brugman,LA Galaxy,0,18,17,5,1.06,0.29,0.00,0.277778
13,Nathan Fogaça,Portland Timbers,1,8,16,4,0.50,0.25,0.06,0.500000
14,Eryk Williamson,Portland Timbers,2,8,23,5,0.35,0.22,0.09,0.625000
15,Maya Yoshida,LA Galaxy,2,16,29,6,0.55,0.21,0.07,0.375000
16,Martín Cáceres,LA Galaxy,0,4,15,3,0.27,0.20,0.00,0.750000
17,Eriq Zavaleta,LA Galaxy,1,2,5,1,0.40,0.20,0.20,0.500000
18,Cristhian Paredes,Portland Timbers,0,9,26,5,0.35,0.19,0.00,0.555556
19,Juan David Mosquera,Portland Timbers,1,17,28,5,0.61,0.18,0.04,0.294118

## Agrupado Time

In [19]:
database.Time.unique()

array(['Inter Miami', 'Real Salt Lake', 'Los Angeles FC',
       'Seattle Sounders FC', 'Columbus Crew', 'Atlanta United',
       'FC Cincinnati', 'Toronto FC', 'Nashville SC',
       'New York Red Bulls', 'Portland Timbers', 'Colorado Rapids',
       'Philadelphia Union', 'Chicago Fire', 'D.C. United',
       'New England Revolution', 'St. Louis City', 'Austin FC',
       'Minnesota United', 'Orlando City', 'CF Montréal', 'FC Dallas',
       'San Jose Earthquakes', 'Charlotte FC', 'New York City FC',
       'Houston Dynamo', 'Sporting Kansas City', 'LA Galaxy',
       'Vancouver Whitecaps FC'], dtype=object)

In [6]:
db_agrupado_time = database.groupby(['Time'], as_index=False).agg(
    Total_Gols=('Gols', 'sum'),
    Total_Chutes=('TC', 'sum'),   # Soma dos chutes ao gol
    Aparicoes=('Data', 'nunique'), # Contagem de jogos únicos (datas únicas)
    Total_Chutes_Gol=('CaG', 'sum') # Soma dos chutes ao gol
)

In [7]:
db_agrupado_time['Média_chute']=round(db_agrupado_time['Total_Chutes'] / db_agrupado_time['Aparicoes'],2)
db_agrupado_time['Média_chute_gol']=round(db_agrupado_time['Total_Chutes_Gol'] / db_agrupado_time['Aparicoes'],2)
db_agrupado_time['Média_gol']=round(db_agrupado_time['Total_Gols'] / db_agrupado_time['Aparicoes'],2)
db_agrupado_time['Taxa_Chutes_Gol'] = db_agrupado_time['Total_Chutes_Gol'] / db_agrupado_time['Total_Chutes']

In [8]:
db_agrupado_time[db_agrupado_time['Time'].isin(['Los Angeles FC','LA Galaxy','Portland Timbers'])].sort_values(by='Total_Chutes', ascending=False, ignore_index= True)

,Time,Total_Gols,Total_Chutes,Aparicoes,Total_Chutes_Gol,Média_chute,Média_chute_gol,Média_gol,Taxa_Chutes_Gol
0,Los Angeles FC,49,422,27,158,15.63,5.85,1.81,0.374408
1,LA Galaxy,57,407,29,166,14.03,5.72,1.97,0.407862
2,Portland Timbers,55,373,28,134,13.32,4.79,1.96,0.359249

## Agrupado por Data

In [9]:
db_desempenho_por_data = database.groupby(['Time', 'Data'], as_index=False).agg(
    Total_Gols=('Gols', 'sum'),          # Soma de gols por data
    Total_Chutes=('TC', 'sum'),          # Soma de chutes por data
    Total_Chutes_Gol=('CaG', 'sum')      # Soma dos chutes ao gol por data
).sort_values(by=['Time', 'Data'])

In [16]:
db_desempenho_por_data['Taxa_Chutes'] = round(db_desempenho_por_data['Total_Gols'] / db_desempenho_por_data['Total_Chutes'],4)
db_desempenho_por_data['Taxa_Chutes_Gol'] = round(db_desempenho_por_data['Total_Gols'] / db_desempenho_por_data['Total_Chutes_Gol'],4)

In [20]:
db_desempenho_por_data[db_desempenho_por_data['Time'].isin(['Los Angeles FC'])].tail(10)

,Time,Data,Total_Gols,Total_Chutes,Total_Chutes_Gol,Taxa_Chutes,Taxa_Chutes_Gol
383,Los Angeles FC,2024-06-19,1,14,1,0.0714,1.0000
384,Los Angeles FC,2024-06-22,6,25,8,0.2400,0.7500
385,Los Angeles FC,2024-06-29,3,22,11,0.1364,0.2727
386,Los Angeles FC,2024-07-04,2,21,6,0.0952,0.3333
387,Los Angeles FC,2024-07-13,1,17,5,0.0588,0.2000
388,Los Angeles FC,2024-07-17,1,9,5,0.1111,0.2000
389,Los Angeles FC,2024-07-20,3,6,4,0.5000,0.7500
390,Los Angeles FC,2024-08-31,0,14,6,0.0000,0.0000
391,Los Angeles FC,2024-09-07,0,7,2,0.0000,0.0000
392,Los Angeles FC,2024-09-14,2,15,5,0.1333,0.4000

In [22]:
db_desempenho_por_data[db_desempenho_por_data['Time'].isin(['Austin FC'])].tail(10)

,Time,Data,Total_Gols,Total_Chutes,Total_Chutes_Gol,Taxa_Chutes,Taxa_Chutes_Gol
46,Austin FC,2024-06-19,1,3,1,0.3333,1.0000
47,Austin FC,2024-06-22,1,9,3,0.1111,0.3333
48,Austin FC,2024-06-29,0,2,0,0.0000,NaN
49,Austin FC,2024-07-06,2,9,4,0.2222,0.5000
50,Austin FC,2024-07-13,0,13,4,0.0000,0.0000
51,Austin FC,2024-07-17,1,11,4,0.0909,0.2500
52,Austin FC,2024-07-20,2,11,4,0.1818,0.5000
53,Austin FC,2024-08-24,2,15,6,0.1333,0.3333
54,Austin FC,2024-08-31,0,6,0,0.0000,NaN
55,Austin FC,2024-09-14,1,17,6,0.0588,0.1667

In [23]:
database

,Jogador,Time,#,Nação,Pos.,Idade,Min.,Gols,Assis.,PB,PT,TC,CaG,CrtsA,CrtV,Contatos,Div,Crts,Bloqueios,xG,npxG,xAG,SCA,GCA,Cmp,Att,Cmp%,PrgP,Conduções,PrgC,Tent,Suc,Data
0,Luis Suárez,Inter Miami,9,URU,FW,37-028,89,0,1,0,0,2,2,0,0,37,0,0,1,0.3,0.3,0.4,6,1,22,31,"71,0",3,24,1,1,1,2024-02-21
1,Leonardo Campana,Inter Miami,8,ECU,FW,23-212,1,0,0,0,0,0,0,0,0,2,0,0,0,0.0,0.0,0.0,0,0,1,2,"50,0",0,1,0,0,0,2024-02-21
2,Robert Taylor,Inter Miami,16,FIN,LW,29-123,75,1,0,0,0,2,1,0,0,31,0,2,1,0.1,0.1,0.2,3,0,20,26,"76,9",2,18,0,2,2,2024-02-21
3,David Ruiz,Inter Miami,41,HON,RM,20-013,15,0,0,0,0,0,0,0,0,11,0,1,0,0.0,0.0,0.0,0,0,10,10,"100,0",0,8,0,0,0,2024-02-21
4,Lionel Messi,Inter Miami,10,ARG,"RW,FW",36-242,90,0,1,0,0,4,1,0,0,84,1,0,0,0.5,0.5,0.2,10,2,56,73,"76,7",15,55,6,4,2,2024-02-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12419,Kamal Miller,Portland Timbers,4,CAN,LB,27-121,90,0,0,0,0,0,0,0,0,59,0,1,3,0.0,0.0,0.0,1,0,44,48,"91,7",5,20,1,2,0,2024-09-14
12420,Dario Župarić,Portland Timbers,13,BIH,CB,32-134,90,0,0,0,0,0,0,0,0,65,2,1,2,0.0,0.0,0.0,1,0,49,56,"87,5",4,31,0,0,0,2024-09-14
12421,Miguel Araujo,Portland Timbers,2,PER,CB,29-326,90,0,1,0,0,1,0,0,0,68,2,1,2,0.0,0.0,0.3,4,1,47,57,"82,5",2,35,0,1,0,2024-09-14
12422,Juan David Mosquera,Portland Timbers,29,COL,RB,22-009,90,0,0,0,0,1,0,0,0,51,1,0,1,0.0,0.0,0.0,2,0,41,45,"91,1",1,24,2,0,0,2024-09-14
12423,Maxime Crépeau,Portland Timbers,16,CAN,GK,30-126,90,0,0,0,0,0,0,0,0,38,0,0,0,0.0,0.0,0.0,0,0,28,37,"75,7",1,25,0,0,0,2024-09-14