In [1]:
import pandas as pd
import re

pd.set_option('display.max_columns', None)

In [2]:
db_temp = pd.read_excel('C://Users//eduar//Desktop//DEV//Football//MLS//database_temp.xlsx')
db = pd.read_excel('C://Users//eduar//Desktop//DEV//Football//MLS//database.xlsx',index_col=None)
db_bu = pd.read_excel('C://Users//eduar//Desktop//DEV//Football//MLS//database_bu.xlsx')

# Criando Backup
db.to_excel('C://Users//eduar//Desktop//DEV//Football//MLS//database_bu.xlsx', index= False)

# Concatenando bases
db_final = pd.concat([db,db_temp], ignore_index= True)

In [3]:
db_final

,Jogador,#,Nação,Pos.,Idade,Min.,Gols,Assis.,PB,PT,TC,CaG,CrtsA,CrtV,Contatos,Div,Crts,Bloqueios,xG,npxG,xAG,SCA,GCA,Cmp,Att,Cmp%,PrgP,Conduções,PrgC,Tent,Suc,Data
0,Luis Suárez,9.0,URU,FW,37-028,89,0,1,0,0,2,2,0,0,37,0,0,1,0.3,0.3,0.4,6,1,22,31,"71,0",3,24,1,1,1,2024-02-21
1,Leonardo Campana,8.0,ECU,FW,23-212,1,0,0,0,0,0,0,0,0,2,0,0,0,0.0,0.0,0.0,0,0,1,2,"50,0",0,1,0,0,0,2024-02-21
2,Robert Taylor,16.0,FIN,LW,29-123,75,1,0,0,0,2,1,0,0,31,0,2,1,0.1,0.1,0.2,3,0,20,26,"76,9",2,18,0,2,2,2024-02-21
3,David Ruiz,41.0,HON,RM,20-013,15,0,0,0,0,0,0,0,0,11,0,1,0,0.0,0.0,0.0,0,0,10,10,"100,0",0,8,0,0,0,2024-02-21
4,Lionel Messi,10.0,ARG,"RW,FW",36-242,90,0,1,0,0,4,1,0,0,84,1,0,0,0.5,0.5,0.2,10,2,56,73,"76,7",15,55,6,4,2,2024-02-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11835,Russell Canouse,6.0,usUSA,CB,29-088,8,0,0,0,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0,0,0,1,"0,0",0,0,0,0,0,2024-09-07
11836,Lucas Bartlett,3.0,usUSA,CB,27-043,90,0,0,0,0,0,0,0,0,57,0,1,0,0.0,0.0,0.0,0,0,37,46,"80,4",2,30,0,0,0,2024-09-07
11837,Christopher McVey,97.0,seSWE,CB,27-148,90,0,0,0,0,0,0,0,0,43,0,0,1,0.0,0.0,0.0,0,0,28,37,"75,7",3,23,1,1,1,2024-09-07
11838,Cristián Dajome,11.0,coCOL,RB,30-248,90,0,0,0,0,1,0,0,0,40,7,1,1,0.0,0.0,0.2,3,0,18,23,"78,3",3,19,2,4,2,2024-09-07
11839,Alex Bono,24.0,usUSA,GK,30-135,90,0,0,0,0,0,0,0,0,28,0,0,0,0.0,0.0,0.0,0,0,13,28,"46,4",0,16,0,0,0,2024-09-07

## Testes

In [11]:
# Agrupar os dados por jogador e calcular a soma dos chutes ao gol e a contagem de aparições
db_agrupado = db.groupby('Jogador').agg(
    Total_Chutes=('TC', 'sum'),   # Soma dos chutes ao gol
    Aparicoes=('Jogador', 'count'), # Contagem de aparições
    Total_Chutes_Gol=('CaG', 'sum'), # Contagem de aparições

).sort_values(by='Total_Chutes', ascending=False)  # Ordenar antes do reset_index

# Adicionar uma coluna de ranking
db_agrupado['Ranking'] = db_agrupado['Total_Chutes'].rank(method='min', ascending=False).astype(int)

# Adicionar uma coluna de média (Total_Chutes / Aparicoes)
db_agrupado['Média_Chutes'] = round(db_agrupado['Total_Chutes'] / db_agrupado['Aparicoes'],2)

db_agrupado['Média_Chutes_Gol'] = round(db_agrupado['Total_Chutes_Gol'] / db_agrupado['Aparicoes'],2)

# Resetar o índice
db_agrupado.reset_index(inplace=True)

# Reorganizar as colunas para que o Ranking seja a primeira
db_agrupado = db_agrupado[['Ranking', 'Jogador', 'Aparicoes','Total_Chutes','Média_Chutes','Total_Chutes_Gol','Média_Chutes_Gol']]

In [12]:
db_agrupado = db_agrupado.sort_values(by=['Média_Chutes'],ascending=False)

In [13]:
db_agrupado

,Ranking,Jogador,Aparicoes,Total_Chutes,Média_Chutes,Total_Chutes_Gol,Média_Chutes_Gol
1,2,Cucho,18,95,5.28,28,1.56
428,428,Kelvin Yeboah,1,5,5.00,1,1.00
26,26,Lionel Messi,12,57,4.75,25,2.08
0,1,Denis Bouanga,23,107,4.65,32,1.39
2,3,Cristian Arango,23,94,4.09,32,1.39
...,...,...,...,...,...,...,...
659,609,Lamine Diack,4,0,0.00,0,0.00
660,609,Tommy Silva,1,0,0.00,0,0.00
661,609,Shane O'Neill,14,0,0.00,0,0.00
662,609,Andres Jasson,3,0,0.00,0,0.00
760,609,Oscar Verhoeven,1,0,0.00,0,0.00