In [1]:
import pandas as pd
import re

pd.set_option('display.max_columns', None)

In [2]:
db_temp = pd.read_csv(r'C:\Users\eduar\OneDrive\Desktop\DEV\Football\MLS\database_temp.csv',delimiter=',')
db = pd.read_csv(r'C:\Users\eduar\OneDrive\Desktop\DEV\Football\MLS\database.csv',delimiter=',')
# Criando Backup
db.to_csv(r'C:\Users\eduar\OneDrive\Desktop\DEV\Football\MLS\database_bu.csv', index= False)

# Concatenando bases
db_final = pd.concat([db,db_temp], ignore_index= True)

In [3]:
db_final

,Jogador,Time,#,Nação,Pos.,Idade,Min.,Gols,Assis.,PB,PT,TC,CaG,CrtsA,CrtV,Contatos,Div,Crts,Bloqueios,xG,npxG,xAG,SCA,GCA,Cmp,Att,Cmp%,PrgP,Conduções,PrgC,Tent,Suc,Data
0,Luis Suárez,Inter Miami,9,URU,FW,37-028,89,0,1,0,0,2,2,0,0,37,0,0,1,0.3,0.3,0.4,6,1,22,31,"71,0",3,24,1,1,1,2024-02-21
1,Leonardo Campana,Inter Miami,8,ECU,FW,23-212,1,0,0,0,0,0,0,0,0,2,0,0,0,0.0,0.0,0.0,0,0,1,2,"50,0",0,1,0,0,0,2024-02-21
2,Robert Taylor,Inter Miami,16,FIN,LW,29-123,75,1,0,0,0,2,1,0,0,31,0,2,1,0.1,0.1,0.2,3,0,20,26,"76,9",2,18,0,2,2,2024-02-21
3,David Ruiz,Inter Miami,41,HON,RM,20-013,15,0,0,0,0,0,0,0,0,11,0,1,0,0.0,0.0,0.0,0,0,10,10,"100,0",0,8,0,0,0,2024-02-21
4,Lionel Messi,Inter Miami,10,ARG,"RW,FW",36-242,90,0,1,0,0,4,1,0,0,84,1,0,0,0.5,0.5,0.2,10,2,56,73,"76,7",15,55,6,4,2,2024-02-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16229,Luis Abram,Atlanta United,4,PER,CB,28-271,90,0,0,0,0,0,0,0,0,44,1,1,1,0.0,0.0,0.0,0,0,33,40,"82,5",2,18,0,0,0,2024-11-24
16230,Derrick Williams,Atlanta United,3,IRL,CB,31-312,90,0,0,0,0,1,0,1,0,64,3,2,1,0.1,0.1,0.0,1,0,46,52,"88,5",2,30,1,0,0,2024-11-24
16231,Stian Rode Gregersen,Atlanta United,5,NOR,CB,29-191,72,0,0,0,0,0,0,0,0,41,3,2,1,0.0,0.0,0.0,1,0,28,31,"90,3",3,12,0,1,1,2024-11-24
16232,Tristan Muyumba,Atlanta United,8,NaN,CM,27-262,18,0,0,0,0,0,0,0,0,22,0,0,0,0.0,0.0,0.0,0,0,21,22,"95,5",3,12,2,1,1,2024-11-24
16233,Brad Guzan,Atlanta United,1,USA,GK,40-076,90,0,0,0,0,0,0,0,0,38,0,0,0,0.0,0.0,0.0,0,0,28,36,"77,8",0,19,0,0,0,2024-11-24

In [4]:
db_final.to_csv(r'C:\Users\eduar\OneDrive\Desktop\DEV\Football\MLS\database.csv', index= False)

## Testes

In [5]:
# Agrupar os dados por jogador e calcular a soma dos chutes ao gol e a contagem de aparições
db_agrupado = db.groupby('Jogador').agg(
    Total_Chutes=('TC', 'sum'),   # Soma dos chutes ao gol
    Aparicoes=('Jogador', 'count'), # Contagem de aparições
    Total_Chutes_Gol=('CaG', 'sum'), # Contagem de aparições

).sort_values(by='Total_Chutes', ascending=False)  # Ordenar antes do reset_index

# Adicionar uma coluna de ranking
db_agrupado['Ranking'] = db_agrupado['Total_Chutes'].rank(method='min', ascending=False).astype(int)

# Adicionar uma coluna de média (Total_Chutes / Aparicoes)
db_agrupado['Média_Chutes'] = round(db_agrupado['Total_Chutes'] / db_agrupado['Aparicoes'],2)

db_agrupado['Média_Chutes_Gol'] = round(db_agrupado['Total_Chutes_Gol'] / db_agrupado['Aparicoes'],2)

# Resetar o índice
db_agrupado.reset_index(inplace=True)

# Reorganizar as colunas para que o Ranking seja a primeira
db_agrupado = db_agrupado[['Ranking', 'Jogador', 'Aparicoes','Total_Chutes','Média_Chutes','Total_Chutes_Gol','Média_Chutes_Gol']]

In [6]:
db_agrupado = db_agrupado.sort_values(by=['Média_Chutes'],ascending=False)

In [7]:
db_agrupado

,Ranking,Jogador,Aparicoes,Total_Chutes,Média_Chutes,Total_Chutes_Gol,Média_Chutes_Gol
2,3,Cucho,26,118,4.54,33,1.27
0,1,Denis Bouanga,31,137,4.42,45,1.45
18,19,Lionel Messi,18,79,4.39,36,2.00
3,4,Cristian Arango,28,110,3.93,40,1.43
4,5,Riqui Puig,28,107,3.82,35,1.25
...,...,...,...,...,...,...,...
693,643,Tarik Scott,2,0,0.00,0,0.00
694,643,Andre Blake,12,0,0.00,0,0.00
695,643,Clint Irwin,5,0,0.00,0,0.00
696,643,Tyler Miller,5,0,0.00,0,0.00
793,643,Henry Wingo,3,0,0.00,0,0.00